### ISSUE TITLE
Error: Rule can only have one resource source (provided resource and test + include + exclude

### ISSUE THREAD

**Issue by rockmelodies** [pl1998/vue_admin#2]
#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- vue-element-admin version:
![image](https://user-images.githubusercontent.com/24653177/118799987-fc917980-b8d1-11eb-82d6-edc3a2902aec.png)

**Comment by pl1998** [comment]
npm安装问题 可以google或者百度解决
